spring:
  application:
    name: myblog
  #激活配置，默认dev
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
## mysql 配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.83.123:3306/myblog
#    username: root
#    password: 23321212

# redis 配置
# todo 需配置Redis   对齐spring：下
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456

server:
  port: 8894
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# Mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 对象存储 配置
# todo 需替换配置
#cos:
#  client:
#    host: xxx
#    accessKey: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx

# springdoc-openapi  knife4j 配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.grey.myblog.controller
# knife 4j 的增量配置
knife4j:
  enable: true
  setting:
    language: zh_cn
